# Generated by Django 3.0.3 on 2021-01-25 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='idea',
            name='title_has_no_leading_and_trailing_whitespaces',
        ),
        migrations.AddConstraint(
            model_name='idea',
            constraint=models.CheckConstraint(check=models.Q(title__iregex='^\\S.*\\S$'), name='title_has_no_leading_and_trailing_whitespaces'),
        ),
    ]
