# Generated by Django 3.0.3 on 2021-01-25 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0002_subtitle_added'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='idea',
            name='title',
        ),
        migrations.AddField(
            model_name='idea',
            name='content_bg',
            field=models.TextField(blank=True, db_tablespace='', verbose_name='Content (Bulgarian)'),
        ),
        migrations.AddField(
            model_name='idea',
            name='content_cs',
            field=models.TextField(blank=True, db_tablespace='', verbose_name='Content (Czech)'),
        ),
        migrations.AddField(
            model_name='idea',
            name='content_da',
            field=models.TextField(blank=True, db_tablespace='', verbose_name='Content (Danish)'),
        ),
        migrations.AddField(
            model_name='idea',
            name='content_de',
            field=models.TextField(blank=True, db_tablespace='', verbose_name='Content (German)'),
        ),
        migrations.AddField(
            model_name='idea',
            name='content_el',
            field=models.TextField(blank=True, db_tablespace='', verbose_name='Content (Greek)'),
        ),
        migrations.AddField(
            model_name='idea',
            name='content_en',
            field=models.TextField(blank=True, db_tablespace='', verbose_name='Content (English)'),
        ),
        migrations.AddField(
            model_name='idea',
            name='content_es',
            field=models.TextField(blank=True, db_tablespace='', verbose_name='Content (Spanish)'),
        ),
        migrations.AddField(
            model_name='idea',
            name='content_et',
            field=models.TextField(blank=True, db_tablespace='', verbose_name='Content (Estonian)'),
        ),
        migrations.AddField(
            model_name='idea',
            name='content_fi',
            field=models.TextField(blank=True, db_tablespace='', verbose_name='Content (Finnish)'),
        ),
        migrations.AddField(
            model_name='idea',
            name='content_fr',
            field=models.TextField(blank=True, db_tablespace='', verbose_name='Content (French)'),
        ),
        migrations.AddField(
            model_name='idea',
            name='content_ga',
            field=models.TextField(blank=True, db_tablespace='', verbose_name='Content (Irish)'),
        ),
        migrations.AddField(
            model_name='idea',
            name='content_hr',
            field=models.TextField(blank=True, db_tablespace='', verbose_name='Content (Croatian)'),
        ),
        migrations.AddField(
            model_name='idea',
            name='content_hu',
            field=models.TextField(blank=True, db_tablespace='', verbose_name='Content (Hungarian)'),
        ),
        migrations.AddField(
            model_name='idea',
            name='content_it',
            field=models.TextField(blank=True, db_tablespace='', verbose_name='Content (Italian)'),
        ),
        migrations.AddField(
            model_name='idea',
            name='content_lt',
            field=models.TextField(blank=True, db_tablespace='', verbose_name='Content (Lithuanian)'),
        ),
        migrations.AddField(
            model_name='idea',
            name='content_lv',
            field=models.TextField(blank=True, db_tablespace='', verbose_name='Content (Latvian)'),
        ),
        migrations.AddField(
            model_name='idea',
            name='content_mt',
            field=models.TextField(blank=True, db_tablespace='', verbose_name='Content (Maltese)'),
        ),
        migrations.AddField(
            model_name='idea',
            name='content_nl',
            field=models.TextField(blank=True, db_tablespace='', verbose_name='Content (Dutch)'),
        ),
        migrations.AddField(
            model_name='idea',
            name='content_pl',
            field=models.TextField(blank=True, db_tablespace='', verbose_name='Content (Polish)'),
        ),
        migrations.AddField(
            model_name='idea',
            name='content_pt',
            field=models.TextField(blank=True, db_tablespace='', verbose_name='Content (Portuguese)'),
        ),
        migrations.AddField(
            model_name='idea',
            name='content_ro',
            field=models.TextField(blank=True, db_tablespace='', verbose_name='Content (Romanian)'),
        ),
        migrations.AddField(
            model_name='idea',
            name='content_sk',
            field=models.TextField(blank=True, db_tablespace='', verbose_name='Content (Slovak)'),
        ),
        migrations.AddField(
            model_name='idea',
            name='content_sl',
            field=models.TextField(blank=True, db_tablespace='', verbose_name='Content (Slovene)'),
        ),
        migrations.AddField(
            model_name='idea',
            name='content_sv',
            field=models.TextField(blank=True, db_tablespace='', verbose_name='Content (Swedish)'),
        ),
        migrations.AddField(
            model_name='idea',
            name='title_bg',
            field=models.CharField(blank=True, db_tablespace='', max_length=200, verbose_name='Title (Bulgarian)'),
        ),
        migrations.AddField(
            model_name='idea',
            name='title_cs',
            field=models.CharField(blank=True, db_tablespace='', max_length=200, verbose_name='Title (Czech)'),
        ),
        migrations.AddField(
            model_name='idea',
            name='title_da',
            field=models.CharField(blank=True, db_tablespace='', max_length=200, verbose_name='Title (Danish)'),
        ),
        migrations.AddField(
            model_name='idea',
            name='title_de',
            field=models.CharField(blank=True, db_tablespace='', max_length=200, verbose_name='Title (German)'),
        ),
        migrations.AddField(
            model_name='idea',
            name='title_el',
            field=models.CharField(blank=True, db_tablespace='', max_length=200, verbose_name='Title (Greek)'),
        ),
        migrations.AddField(
            model_name='idea',
            name='title_en',
            field=models.CharField(blank=True, db_tablespace='', max_length=200, verbose_name='Title (English)'),
        ),
        migrations.AddField(
            model_name='idea',
            name='title_es',
            field=models.CharField(blank=True, db_tablespace='', max_length=200, verbose_name='Title (Spanish)'),
        ),
        migrations.AddField(
            model_name='idea',
            name='title_et',
            field=models.CharField(blank=True, db_tablespace='', max_length=200, verbose_name='Title (Estonian)'),
        ),
        migrations.AddField(
            model_name='idea',
            name='title_fi',
            field=models.CharField(blank=True, db_tablespace='', max_length=200, verbose_name='Title (Finnish)'),
        ),
        migrations.AddField(
            model_name='idea',
            name='title_fr',
            field=models.CharField(blank=True, db_tablespace='', max_length=200, verbose_name='Title (French)'),
        ),
        migrations.AddField(
            model_name='idea',
            name='title_ga',
            field=models.CharField(blank=True, db_tablespace='', max_length=200, verbose_name='Title (Irish)'),
        ),
        migrations.AddField(
            model_name='idea',
            name='title_hr',
            field=models.CharField(blank=True, db_tablespace='', max_length=200, verbose_name='Title (Croatian)'),
        ),
        migrations.AddField(
            model_name='idea',
            name='title_hu',
            field=models.CharField(blank=True, db_tablespace='', max_length=200, verbose_name='Title (Hungarian)'),
        ),
        migrations.AddField(
            model_name='idea',
            name='title_it',
            field=models.CharField(blank=True, db_tablespace='', max_length=200, verbose_name='Title (Italian)'),
        ),
        migrations.AddField(
            model_name='idea',
            name='title_lt',
            field=models.CharField(blank=True, db_tablespace='', max_length=200, verbose_name='Title (Lithuanian)'),
        ),
        migrations.AddField(
            model_name='idea',
            name='title_lv',
            field=models.CharField(blank=True, db_tablespace='', max_length=200, verbose_name='Title (Latvian)'),
        ),
        migrations.AddField(
            model_name='idea',
            name='title_mt',
            field=models.CharField(blank=True, db_tablespace='', max_length=200, verbose_name='Title (Maltese)'),
        ),
        migrations.AddField(
            model_name='idea',
            name='title_nl',
            field=models.CharField(blank=True, db_tablespace='', max_length=200, verbose_name='Title (Dutch)'),
        ),
        migrations.AddField(
            model_name='idea',
            name='title_pl',
            field=models.CharField(blank=True, db_tablespace='', max_length=200, verbose_name='Title (Polish)'),
        ),
        migrations.AddField(
            model_name='idea',
            name='title_pt',
            field=models.CharField(blank=True, db_tablespace='', max_length=200, verbose_name='Title (Portuguese)'),
        ),
        migrations.AddField(
            model_name='idea',
            name='title_ro',
            field=models.CharField(blank=True, db_tablespace='', max_length=200, verbose_name='Title (Romanian)'),
        ),
        migrations.AddField(
            model_name='idea',
            name='title_sk',
            field=models.CharField(blank=True, db_tablespace='', max_length=200, verbose_name='Title (Slovak)'),
        ),
        migrations.AddField(
            model_name='idea',
            name='title_sl',
            field=models.CharField(blank=True, db_tablespace='', max_length=200, verbose_name='Title (Slovene)'),
        ),
        migrations.AddField(
            model_name='idea',
            name='title_sv',
            field=models.CharField(blank=True, db_tablespace='', max_length=200, verbose_name='Title (Swedish)'),
        ),
    ]
