# Generated by Django 3.0.3 on 2021-01-25 04:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '__first__'),
        ('ideas', '0004_copy_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idea',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category_ideas', to='categories.Category', verbose_name='Category'),
        ),
    ]
