# Generated by Django 3.0.3 on 2021-01-25 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '__first__'),
        ('ideas', '0005_auto_20210124_2254'),
    ]

    operations = [
        migrations.AddField(
            model_name='idea',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='ideas', to='categories.Category', verbose_name='Categories'),
        ),
    ]
