# Generated by Django 3.0.3 on 2021-01-25 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0006_idea_categories'),
    ]

    operations = [
    ]
