# Generated by Django 3.0.3 on 2021-02-12 02:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ideas', '0007_copy_categories'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ideatranslations',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='ideatranslations',
            name='idea',
        ),
        migrations.AlterModelOptions(
            name='like',
            options={'verbose_name': 'Like', 'verbose_name_plural': 'Likes'},
        ),
        migrations.RemoveConstraint(
            model_name='idea',
            name='unique_titles_for_each_author',
        ),
        migrations.RemoveConstraint(
            model_name='idea',
            name='title_has_no_leading_and_trailing_whitespaces',
        ),
        migrations.RemoveField(
            model_name='idea',
            name='category',
        ),
        migrations.AddField(
            model_name='idea',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Creation Date and Time'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='idea',
            name='meta_author',
            field=models.CharField(blank=True, max_length=255, verbose_name='Author'),
        ),
        migrations.AddField(
            model_name='idea',
            name='meta_copyright',
            field=models.CharField(blank=True, max_length=255, verbose_name='Copyright'),
        ),
        migrations.AddField(
            model_name='idea',
            name='meta_description',
            field=models.CharField(blank=True, max_length=255, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='idea',
            name='meta_keywords',
            field=models.CharField(blank=True, help_text='Separate keywords with commas.', max_length=255, verbose_name='Keywords'),
        ),
        migrations.AddField(
            model_name='idea',
            name='modified',
            field=models.DateTimeField(auto_now=True, verbose_name='Modification Date and Time'),
        ),
        migrations.AlterField(
            model_name='idea',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authored_ideas', to=settings.AUTH_USER_MODEL, verbose_name='Author'),
        ),
        migrations.AlterField(
            model_name='idea',
            name='content_en',
            field=models.TextField(db_tablespace='', verbose_name='Content (English)'),
        ),
        migrations.AlterField(
            model_name='idea',
            name='title_en',
            field=models.CharField(db_tablespace='', max_length=200, verbose_name='Title (English)'),
        ),
        migrations.AddConstraint(
            model_name='idea',
            constraint=models.UniqueConstraint(condition=models.Q(_negated=True, author=None), fields=('title_en',), name='unique_titles_for_each_author'),
        ),
        migrations.AddConstraint(
            model_name='idea',
            constraint=models.CheckConstraint(check=models.Q(title_en__iregex='^\\S.*\\S$'), name='title_has_no_leading_and_trailing_whitespaces'),
        ),
        migrations.DeleteModel(
            name='IdeaTranslations',
        ),
    ]
